// Generated by CoffeeScript 1.12.5
(function() {
  var Form, Renderer, _, ionic1;

  _ = require('lodash');

  Renderer = require('./ionic1.coffee');

  ionic1 = new Renderer();

  Form = (function() {
    Form.prototype.include = '__all__';

    Form.prototype.exlcude = [];


    /*
    opts:
      model:
        attributes:
          name:
            type: 'string'
          ...
      include: [attr1, attr2, ...] or '__all__' to include all attributes
      exclude: [attr1, attr2, ...] or null to exclude none
     */

    function Form(opts) {
      if (opts == null) {
        opts = {};
      }
      if (!('model' in opts)) {
        throw new Error('model definition not yet defined for model form');
      }
      _.extend(this, opts);
    }

    Form.prototype.html = function(values, renderer) {
      if (values == null) {
        values = {};
      }
      if (renderer == null) {
        renderer = ionic1;
      }
      return renderer.html(this, values);
    };

    return Form;

  })();

  module.exports = Form;

}).call(this);
